parameters:
  - name: jobName
    type: string
    default: functionDeploy
  - name: dependsOn
    type: object
    default: []
  - name: condition
    type: string
    default: succeeded()
  - name: displayName
    type: string
    default: Function App Deploy
  - name: serviceConnection
    type: string
  - name: azureSubscription
    type: string
  - name: deployArtifactName
    type: string
  - name: deployArtifactsPath
    type: string
    default: $(Pipeline.Workspace)
  - name: deployKeyVaultName
    type: string
    default: ''
  - name: deployKeyVaultResourceGroup
    type: string
    default: ''
  - name: appName
    type: string
  - name: deploySecretsFilter
    type: string
    default: '*'
  - name: javaVersion
    type: string
    default: '21'
  - name: workingDirectory
    type: string
    default: '.'
  - name: envs
    type: object
    default: {}

jobs:
  - job: ${{ parameters.jobName }}
    dependsOn: ${{ parameters.dependsOn }}
    condition: ${{ parameters.condition }}
    displayName: ${{ parameters.displayName }}

    steps:
      - ${{ if ne(parameters.deployKeyVaultName, '') }}:
        - ${{ if ne(parameters.deployKeyVaultResourceGroup, '') }}:
          - template: ../tasks/az-keyvault-network-rule.yaml
            parameters:
              action: add
              azureServiceConnection: ${{ parameters.serviceConnection }}
              keyVaultName: ${{ parameters.deployKeyVaultName }}
              keyVaultResourceGroup: ${{ parameters.deployKeyVaultResourceGroup }}

        - task: AzureKeyVault@2
          displayName: Get variables from Key Vault
          inputs:
            connectedServiceName: ${{ parameters.serviceConnection }}
            keyVaultName: ${{ parameters.deployKeyVaultName }}
            secretsFilter: ${{ parameters.deploySecretsFilter }}

        - ${{ if ne(parameters.deployKeyVaultResourceGroup, '') }}:
          - template: ../tasks/az-keyvault-network-rule.yaml
            parameters:
              action: remove
              azureServiceConnection: ${{ parameters.serviceConnection }}
              keyVaultName: ${{ parameters.deployKeyVaultName }}
              keyVaultResourceGroup: ${{ parameters.deployKeyVaultResourceGroup }}

      - task: replacetokens@5
        displayName: Replace tokens
        inputs:
          rootDirectory: "${{ parameters.deployArtifactsPath }}/s/${{ parameters.deployArtifactName}} "
          targetFiles: "*.yaml"
          actionOnMissing: continue
          keepToken: true

      - task: AppSettingsBuilder@1
        inputs:
          file: "${{ parameters.deployArtifactsPath }}/s/${{ parameters.deployArtifactName}}/env.yaml "
          stage: 'dev'
          logdir: appsettings
          forbiddenKeywords: 'test,tests,qa,uat,dev'

      - task: AzureCLI@2
        displayName: Apply App Settings
        inputs:
          azureSubscription: ${{ parameters.serviceConnection }}
          scriptType: bash
          scriptLocation: inlineScript
          arguments: '${{ parameters.azureSubscription }} ${{ parameters.deployKeyVaultResourceGroup }} alx-sftp-function env/dev.json'
          inlineScript: |
            az account set --subscription $1
                
            if [ -f "$4" ]; then
              az functionapp config appsettings set -g $2 -n $3 --settings @$4
            fi
            
      - task: JavaToolInstaller@0
        displayName: Install Java
        inputs:
          versionSpec: ${{ parameters.javaVersion }}
          jdkArchitectureOption: x64
          jdkSourceOption: PreInstalled

      - task: FuncToolsInstaller@0
        displayName: Install Azure Functions Core Tools
        inputs:
          version: latest

      - task: AzureCLI@2
        displayName: Azure Function Deploy
        inputs:
          azureSubscription: ${{ parameters.serviceConnection }}
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            az account set --subscription ${{ parameters.azureSubscription }}

            if [ "${{ parameters.workingDirectory }}" != "." ]; then
              bash ./gradlew :${{ parameters.workingDirectory }}:azureFunctionsDeploy
            else
              bash ./gradlew azureFunctionsDeploy
            fi
        env:
          ${{ each env in parameters.envs }}:
            ${{ env.key }}: ${{ env.value }}
      
