parameters:
  - name: deployJobName
    type: string
    default: deploy
  - name: deployDependsOn
    type: object
    default: []
  - name: deployCondition
    type: string
    default: "succeeded()"
  - name: deployEnvironment
    type: string
  - name: deployAppName
    type: string
  - name: deployArtifactName
    type: string
    default: "functionapp"
  - name: deployArtifactsPath
    type: string
    default: "$(Pipeline.Workspace)"
  - name: deployAzureServiceConnection
    type: string
    default: ''
  - name: deployKeyVaultResourceGroup
    type: string
    default: ''
  - name: deployKeyVaultName
    type: string
    default: ''
  - name: deploySecretsFilter
    type: string
    default: "*"
  - name: javaVersion
    type: string
    default: "17"
  - name: azureSubscription
    type: string
  - name: workingDirectory
    type: string
    default: "."
  - name: envs
    type: object
    default: {}

jobs:
  - deployment: ${{ parameters.deployJobName }}
    dependsOn: ${{ parameters.deployDependsOn }}
    condition: ${{ parameters.deployCondition }}
    environment: ${{ parameters.deployEnvironment }}
    displayName: "Deploy Azure Function App"
    strategy:
      runOnce:
        deploy:
          steps:
            - ${{ if ne(parameters.deployKeyVaultName, '') }}:
              - ${{ if ne(parameters.deployKeyVaultResourceGroup, '') }}:
                - template: "../tasks/az-keyvault-network-rule.yaml"
                  parameters:
                    action: add
                    azureServiceConnection: ${{ parameters.deployAzureServiceConnection }}
                    keyVaultName: ${{ parameters.deployKeyVaultName }}
                    keyVaultResourceGroup: ${{ parameters.deployKeyVaultResourceGroup }}

              - task: AzureKeyVault@2
                displayName: "Getting Variables from Key Vault"
                inputs:
                  connectedServiceName: ${{ parameters.deployAzureServiceConnection }}
                  keyVaultName: ${{ parameters.deployKeyVaultName }}
                  secretsFilter: ${{ parameters.deploySecretsFilter }}

              - ${{ if ne(parameters.deployKeyVaultResourceGroup, '') }}:
                - template: "../tasks/az-keyvault-network-rule.yaml"
                  parameters:
                    action: remove
                    azureServiceConnection: ${{ parameters.deployAzureServiceConnection }}
                    keyVaultName: ${{ parameters.deployKeyVaultName }}
                    keyVaultResourceGroup: ${{ parameters.deployKeyVaultResourceGroup }}

            - task: DownloadBuildArtifacts@1
              displayName: "Download Build Artifacts"
              inputs:
                downloadType: specific
                itemPattern: ${{ parameters.deployArtifactName }}/**
                downloadPath: ${{ parameters.deployArtifactsPath }}
            
            - task: CmdLine@2
              inputs:
                script: 'pwd && ls -laR'
            
            - task: replacetokens@5
              displayName: "Replace Values"
              inputs:
                rootDirectory: "${{ parameters.deployArtifactsPath }}/${{ parameters.deployArtifactName }}"
                targetFiles: "*.yaml"
                actionOnMissing: continue
                keepToken: true

            - task: JavaToolInstaller@0
              displayName: "Install Java"
              inputs:
                versionSpec: ${{ parameters.javaVersion }}
                jdkArchitectureOption: "x64"
                jdkSourceOption: "PreInstalled"

            - task: FuncToolsInstaller@0
              displayName: "Install Azure Functions Core Tools"
              inputs:
                version: latest

            - task: AzureCLI@2
              displayName: "Deploy Azure Function App"
              inputs:
                azureSubscription: ${{ parameters.deployAzureServiceConnection }}
                scriptType: bash
                scriptLocation: inlineScript
                inlineScript: |
                  az account set --subscription ${{ parameters.azureSubscription }}

                  cd "${{ parameters.deployArtifactsPath }}/${{ parameters.deployArtifactName }}"

                  if [ "${{ parameters.workingDirectory }}" != "." ]; then
                    bash ./gradlew :${{ parameters.workingDirectory }}:azureFunctionsDeploy
                  else
                    bash ./gradlew azureFunctionsDeploy
                  fi
              env:
                ${{ each env in parameters.envs }}:
                  ${{ env.key }}: ${{ env.value }}
