parameters:
  - name: stageName
    type: string
  - name: dependsOn
    type: object
    default: []
  - name: condition
    type: string
    default: "succeeded()"
  - name: displayName
    type: string
  - name: acrOriginName
    type: string
  - name: containerRegistry
    type: string
  - name: appName
    type: string
  - name: manifestToPublish
    type: string
    default: kubernetes
  - name: dockerArgs
    type: string
    default: ''
  - name: dockerFile
    type: string
    default: "./Dockerfile"
  - name: imageScan
    type: boolean
    default: false
  - name: scanIgnoreUnfixed
    type: boolean
    default: true
  - name: scanVulnType
    type: string
    default: "os"
  - name: tag
    type: string
    default: $(Build.SourceBranchName)-$(Build.BuildId)
  - name: scanSeverity
    type: string
    default: HIGH,CRITICAL
  - name: artifactName
    type: string
    default: kubernetes
  - name: trivyVersion
    type: string
    default: "0.46.0"
  - name: scanContinueOnError
    type: boolean
    default: false
  - name: azureSubscriptionOrigin
    type: string
    default: ''
  - name: acrDestinations
    type: object
    default: []
  - name: scanDBRepository
    type: string
    default: "ghcr.io/aquasecurity/trivy-db"

stages:
  - stage: ${{ parameters.stageName }}
    dependsOn: ${{ parameters.dependsOn }}
    condition: ${{ parameters.condition }}
    displayName: ${{ parameters.displayName }}
    jobs:
      - template: "../jobs/build-and-push-image-to-acr.yaml"
        parameters:
          buildAppName: ${{ parameters.appName }}
          buildAcrOriginName: ${{ parameters.acrOriginName }}
          buildContainerRegistry: ${{ parameters.containerRegistry }}
          buildTags: ${{ parameters.tag }}
          buildDockerArgs: ${{ parameters.dockerArgs }}
          buildDockerFile: ${{ parameters.dockerFile }}
          buildArtifactName: ${{ parameters.artifactName }}
          buildManifestToPublish: ${{ parameters.manifestToPublish }}
          buildAzureSubscriptionOrigin: ${{ parameters.azureSubscriptionOrigin }}
          buildAcrDestinations: ${{ parameters.acrDestinations }}
          
      - ${{ if eq(parameters.imageScan, true) }}:
        - template: "../jobs/trivy-scan.yaml"
          parameters:
            scanDependsOn: build
            scanTrivyVersion: ${{ parameters.trivyVersion }}
            scanContinueOnError: ${{ parameters.scanContinueOnError }}
            scanContainerRegistry: ${{ parameters.containerRegistry }}
            scanRepository: ${{ parameters.acrOriginName }}.azurecr.io
            scanImage: ${{ parameters.appName }}
            scanTag: ${{ parameters.tag }}
            scanSeverity: ${{ parameters.scanSeverity }}
            scanIgnoreUnfixed: ${{ parameters.scanIgnoreUnfixed }}
            scanVulnType: ${{ parameters.scanVulnType }}
            scanDBRepository: ${{ parameters.scanDBRepository }}